-- 게시판 영구 삭제용 명령어
DROP TABLE hell_board PURGE;

-- 테스트용 게시판(board) 테이블
CREATE TABLE hell_board(
	bno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	 -- 글 번호
	title VARCHAR2(300) NOT NULL,										 -- 제목
	content CLOB NOT NULL,												 -- 내용
--	writer VARCHAR2(50),												 -- 작성자
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,						 -- 작성일
	viewcnt NUMBER DEFAULT 0,											 -- 조회수
	agree NUMBER DEFAULT 0,												 -- 추천수
	disagree NUMBER DEFAULT 0,											 -- 비추천수
	anonymous NUMBER(1) DEFAULT 1										 -- 익명 여부
);

INSERT INTO hell_board(bno, title, content, writer)
VALUES(1, '헬스장 내돈내산 이용후기', '패스권 신청할때부터 너무많은 종목이있어서 머리아팠는데요 그래도
나름 다양한 운동을 즐길수있어서 좋은거같아요 다른분들도 신청해서 많은 운동 체험해보세요!', '최기근');


INSERT INTO hell_board(bno, title, content, writer)
VALUES(2, '이번에 필라테스 신청했어요', '여러가지 운동 체험하다 필라테스에 꽂혀서 신청하게되었어요
제 몸엔 필라테스같은 운동이 잘맞더라고요, 확실히 여러가지해보니까 나한테 맞는거 하나는 찾게되는거같아요', '김수정');

INSERT INTO hell_board(bno, title, content, writer)
VALUES(3, '역시 운동은 여러가지 해야합니다', '그래야 자기한테 맞는걸하죠, 체육관돌아다니며 가르치는분들도 많이 만나봐야 판단하죠', '이지황');

INSERT INTO hell_board(bno, title, content, writer)
VALUES(4, '이번에 신청해볼까합니다.', '해본분들 후기 보니까 괜찮아 보여서 신청한건 해봐야겠네요', '이희승');

INSERT INTO hell_board(bno, title, content, writer)
VALUES(5, '아직 풋살이나 족구같은건없네요', '저도 헬스다니면서 알게된 사이트인데, 기존 축구나 배드민턴 이렇게 사람들이 많이즐기시는
스포츠관련해서도 이런 플랫폼이 있으면 좋겠네요', '김진영');

INSERT INTO hell_board(bno, title, content, writer)
VALUES(6, '이 플랫폼 좋네요', '여러가지 배워보면서 몸도풀리고 기간제 상품이 아니어서 저한테 맞출수있으니 좋네요', '양진곤');

INSERT INTO hell_board(bno, title, content, writer)
VALUES(7, '시작해볼까합니다', '맞는운동찾을수있을지 걱정이에요', '박지민');

-- 글 복사하기
INSERT INTO hell_board(title, content, writer) 
SELECT title, content, writer FROM hell_board;

-- 테이블 전체 조회
SELECT * FROM hell_board;

-- 테이블 내림차순
SELECT * FROM hell_board ORDER BY bno DESC;

-- 추천수 20으로 설정하기
UPDATE hell_board
SET AGREE = 20
WHERE bno IN (2,3);


DELETE FROM hell_board
WHERE bno = 2 ;

-- 익명 게시판 할때 쓰는거
ALTER TABLE hell_board ADD anonymous NUMBER(1) DEFAULT 0; -- 0: 공개, 1: 익명

-- 익명 게시판 할때 쓰는거 없애는거
ALTER TABLE hell_board
DROP COLUMN anonymous;

COMMIT

-- 7번글 추천수 보기
SELECT agree FROM hell_board WHERE bno = 7

-- 모든 게시글의 조회수와 추천수 초기화
UPDATE hell_board
SET viewcnt = 0,
    agree = 0;

------------------------------------------------------------ 익명게시판 ------------------------------------------------------------
CREATE TABLE secret_board (
    bno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(300),
    content CLOB,
    nickname VARCHAR2(50), -- 익명 게시판에서 사용할 닉네임
    password VARCHAR2(100),
    regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    viewcnt NUMBER DEFAULT 0,
    agree NUMBER DEFAULT 0,
    disagree NUMBER DEFAULT 0
);

INSERT INTO secret_board(bno, title, content, nickname)
VALUES(1, '헬스장 내돈내산 이용후기', '패스권 신청할때부터 너무많은 종목이있어서 머리아팠는데요 그래도
나름 다양한 운동을 즐길수있어서 좋은거같아요 다른분들도 신청해서 많은 운동 체험해보세요!', 'ㅇㅇ고닉');

INSERT INTO secret_board(bno, title, content, nickname)
VALUES(2, '시작해볼까합니다', '맞는운동찾을수있을지 걱정이에요', 'ㅇㅇ반고닉');

DELETE FROM secret_board
WHERE bno = 1 ;

SELECT * FROM SECRET_BOARD;

COMMIT
------------------------------------------------------------ 지역게시판 ------------------------------------------------------------

-- 게시판 영구 삭제용 명령어
DROP TABLE local_board PURGE;

CREATE TABLE local_board (
    bno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(300),
    content CLOB,
    nickname VARCHAR2(50), 
    regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    viewcnt NUMBER DEFAULT 0,
    agree NUMBER DEFAULT 0,
    disagree NUMBER DEFAULT 0,
    category_id INT,
    FOREIGN KEY (category_id) REFERENCES local_category(category_id)
);

SELECT * FROM local_board;

 -- DROP TABLE local_category PURGE;

CREATE TABLE local_category (
    category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50)
);

INSERT INTO local_category (category_name) VALUES ('서울');
INSERT INTO local_category (category_name) VALUES ('부산');
INSERT INTO local_category (category_name) VALUES ('대구');
INSERT INTO local_category (category_name) VALUES ('인천');
INSERT INTO local_category (category_name) VALUES ('광주');
INSERT INTO local_category (category_name) VALUES ('대전');
INSERT INTO local_category (category_name) VALUES ('울산');
INSERT INTO local_category (category_name) VALUES ('수원');
INSERT INTO local_category (category_name) VALUES ('성남');
INSERT INTO local_category (category_name) VALUES ('청주');
INSERT INTO local_category (category_name) VALUES ('천안');
INSERT INTO local_category (category_name) VALUES ('전주');
INSERT INTO local_category (category_name) VALUES ('군산');
INSERT INTO local_category (category_name) VALUES ('순천');
INSERT INTO local_category (category_name) VALUES ('목포');

SELECT * FROM local_category;

INSERT INTO local_board(bno, title, content, nickname, category_id)
VALUES(1, '헬스장 내돈내산 이용후기', '패스권 신청할때부터 너무많은 종목이있어서 머리아팠는데요 그래도
나름 다양한 운동을 즐길수있어서 좋은거같아요 다른분들도 신청해서 많은 운동 체험해보세요!', 'ㅇㅇ고닉', 1);



COMMIT


	
	








