CREATE TABLE seoul_board(
	bno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	 -- 글 번호
	title VARCHAR2(300) NOT NULL,										 -- 제목
	content CLOB NOT NULL,												 -- 내용
	writer VARCHAR2(50),												 -- 작성자
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,						 -- 작성일
	viewcnt NUMBER DEFAULT 0,											 -- 조회수
	agree NUMBER DEFAULT 0,												 -- 추천수
	disagree NUMBER DEFAULT 0,											 -- 비추천수
	anonymous NUMBER(1) DEFAULT 1										 -- 익명 여부
);